[workspace]

members = [
  "medic-check-postgres",
]
resolver = "1"

[workspace.dependencies]
clap = { version = "4.1.8" }
envsubst = "0.2"
indoc = "2.0.1"
medic-lib = { git = "https://github.com/synchronal/medic-rs", tag = "v0.2.1" }
postgres = "0.19"
